name: remote ssh ec2_temp
on: 
  label:
    types:
      - created
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Container
        run: | 
          echo ${{ github.repository }}
            
            
             


# SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
# REMOTE_HOST: ${{ secrets.SSH_HOST }}
# REMOTE_USER: ${{ secrets.USER_NAME }}
                
