# we can make use of matrix 

name: remote ssh ec2_temp
on:
  push:
    branches:
      - main
jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: easingthemes/ssh-deploy@v5.0.0
        name: Check Container
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          SCRIPT_AFTER: |
  pipeline:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: easingthemes/ssh-deploy@v5.0.0
        name: Build_1
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          SCRIPT_AFTER: |
              cd /home/code/git_project/dell_workbench_workflow/src
              sudo python3 training.py
  # Preprocess:
  #   needs: Datasource
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: easingthemes/ssh-deploy@v5.0.0
  #       name: Build_2
  #       with:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         REMOTE_HOST: ${{ secrets.SSH_HOST }}
  #         REMOTE_USER: ${{ secrets.USER_NAME }}
  #         SCRIPT_AFTER: |
  #             cd ${{ github.event.repository.name }}
  #             cd _project_root/_src
  #             python3 preprocess.py
  # Training:
  #   needs: Preprocess
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: easingthemes/ssh-deploy@v5.0.0
  #       name: Build_3
  #       with:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         REMOTE_HOST: ${{ secrets.SSH_HOST }}
  #         REMOTE_USER: ${{ secrets.USER_NAME }}
  #         SCRIPT_AFTER: |
  #             cd ${{ github.event.repository.name }}
  #             cd _project_root/_src
  #             python3 training.py

          
