name: remote ssh ec2_temp
on: 
  label:
    types:
      - created
jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: easingthemes/ssh-deploy@v5.0.0
        name: Check Container
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          SCRIPT_AFTER: |
              sudo mkdir /home/code
              cd /home/code
              sudo git clone https://github.com/${{ github.repository }}
  run_1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: easingthemes/ssh-deploy@v5.0.0
        name: Check Container
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          SCRIPT_AFTER: |
              cd ${{ github.event.repository.name }}
              cd _project_root/_src
              python3 datasource.py
  run_2:
    needs: run_1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: easingthemes/ssh-deploy@v5.0.0
        name: Check Container
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          SCRIPT_AFTER: |
              cd ${{ github.event.repository.name }}
              cd _project_root/_src
              python3 preprocess.py
  run_3:
    needs: run_2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: easingthemes/ssh-deploy@v5.0.0
        name: Check Container
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          SCRIPT_AFTER: |
              cd ${{ github.event.repository.name }}
              cd _project_root/_src
              python3 training.py

          
