name: remote ssh ec2_temp
on: 
  label:
    types:
      - created
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: easingthemes/ssh-deploy@v5.0.0
        name: Check Container
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          SCRIPT_AFTER: |
              cd /home/
              git clone https://github.com/${{ github.repository }}
              cd ${{ github.repository }}
              ls

          
