name: remote ssh command
on: 
  label:
    types:
      - created
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - uses: easingthemes/ssh-deploy@v5.0.0
          name: Deploy over SSH
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.SSH_HOST }}
            REMOTE_USER: ${{ secrets.USER_NAME }}
            SCRIPT_AFTER: |
                
